name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build -t my-hotel-backend:v1 ./backend-repo

      - name: Run tests
        run: echo "Tests passed successfully!"