name: Deployment Preparation

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  update-manifests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          path: main-repo

      - name: Checkout infra-repo
        uses: actions/checkout@v4
        with:
           repository: 'eli0504167101/infra-repo'
           path: 'infra-repo'
           token: ${{ secrets.PAT_TOKEN }}

      - name: Debug - List directory structure
        run: |
          echo "Current directory: $(pwd)"
          find . -maxdepth 4 -not -path '*/.*'

      - name: List files to debug
        run: |
          echo "Listing files in infra-repo:"
          find infra-repo -maxdepth 3

      - name: Update Image Tags
        run: |
          # הגדרת נתיבים
          BACKEND_YAML="infra-repo/kubernetes/deployments/backend-deployment.yaml"
          FRONTEND_YAML="infra-repo/kubernetes/deployments/frontend-deployment.yaml"

          # בדיקת קיום הקבצים
          if [ -f "$BACKEND_YAML" ] && [ -f "$FRONTEND_YAML" ]; then
              echo "Updating image tags to ${{ github.run_number }}..."
              
              # Backend
sed -i "s|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/hotel-backend:${{ github.run_number }}|g" "$BACKEND_YAML"

# Frontend
sed -i "s|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/hotel-frontend:${{ github.run_number }}|g" "$FRONTEND_YAML"
          else
              echo "Error: One or more deployment files not found!" && exit 1
          fi